# Generated by Django 3.2.4 on 2021-06-12 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="vote_count",
            field=models.CharField(
                max_length=20, validators=[django.core.validators.int_list_validator]
            ),
        ),
    ]
