# Generated by Django 3.2.4 on 2021-07-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='step',
            field=models.IntegerField(choices=[(0, 'HOH Competition'), (1, 'Nom Ceremony'), (2, 'POV Competition'), (3, 'Veto Ceremony'), (4, 'Eviction'), (5, 'Finale'), (6, 'Memory Wall')], default=6),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('vote_count', models.CharField(default='', max_length=10)),
                ('tied', models.BooleanField(default=False)),
                ('evicted', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evicted_weeks', to='simulator.houseguest')),
                ('final_nominees', models.ManyToManyField(default=[], related_name='final_noms_weeks', to='simulator.Houseguest')),
                ('hoh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='simulator.houseguest')),
                ('initial_nominees', models.ManyToManyField(default=[], related_name='initial_noms_weeks', to='simulator.Houseguest')),
                ('pov', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pov_weeks', to='simulator.houseguest')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='weeks',
            field=models.ManyToManyField(default=[], related_name='game_weeks', to='simulator.Week'),
        ),
    ]
