# Generated by Django 3.2 on 2021-05-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseguest',
            name='competition_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houseguest',
            name='evicted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseguest',
            name='immune',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseguest',
            name='nomination_count',
            field=models.IntegerField(default=0),
        ),
    ]
