# Generated by Django 3.2 on 2021-05-29 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_game_user_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_user_player', to='simulator.houseguest'),
        ),
    ]
