# Generated by Django 3.2 on 2021-05-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='simulator.houseguest'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='simulator.Houseguest'),
        ),
    ]
