# Generated by Django 3.2.4 on 2021-07-24 23:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_game_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='vote_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
