# Generated by Django 3.2 on 2021-05-02 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_auto_20210501_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetoPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.houseguest')),
                ('nominees', models.ManyToManyField(related_name='veto_player_nominees', to='simulator.Houseguest')),
                ('participants', models.ManyToManyField(related_name='veto_player_participants', to='simulator.Houseguest')),
            ],
        ),
    ]
