# Generated by Django 3.2.4 on 2021-07-24 23:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_alter_week_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='vote_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
