# Generated by Django 3.2 on 2021-05-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_vetoplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetoplayers',
            name='picked',
            field=models.ManyToManyField(default=[], related_name='picked_players', to='simulator.Houseguest'),
        ),
    ]
