# Generated by Django 3.2.4 on 2021-07-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_alter_week_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.IntegerField(),
        ),
    ]
