# Generated by Django 3.2 on 2021-05-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_vetoplayers_picked'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetoCeremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veto_meeting_hoh', to='simulator.houseguest')),
                ('nominees', models.ManyToManyField(related_name='veto_meeting_noms', to='simulator.Houseguest')),
                ('participants', models.ManyToManyField(related_name='veto_meeting_participants', to='simulator.Houseguest')),
                ('veto_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veto_meeting_pov', to='simulator.houseguest')),
            ],
        ),
    ]
