# Generated by Django 3.2 on 2021-05-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_vetoceremony'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetoceremony',
            name='using',
            field=models.BooleanField(default=None),
        ),
    ]
