# Generated by Django 3.2 on 2021-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_vetoceremony_using'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetoceremony',
            name='using',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
