# Generated by Django 3.2 on 2021-05-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_alter_vetoceremony_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetoceremony',
            name='final_nominees',
            field=models.ManyToManyField(related_name='veto_meeting_final_noms', to='simulator.Houseguest'),
        ),
        migrations.AlterField(
            model_name='vetoceremony',
            name='nominees',
            field=models.ManyToManyField(related_name='veto_meeting_init_noms', to='simulator.Houseguest'),
        ),
    ]
