# Generated by Django 3.2 on 2021-05-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_auto_20210502_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetoceremony',
            name='final_nominees',
        ),
    ]
