# Generated by Django 3.2 on 2021-05-02 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_alter_evictionceremony_evicted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('evicted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_evicted', to='simulator.houseguest')),
                ('final_nominees', models.ManyToManyField(related_name='week_final_noms', to='simulator.Houseguest')),
                ('hoh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_hoh', to='simulator.houseguest')),
                ('inital_nominees', models.ManyToManyField(related_name='week_init_noms', to='simulator.Houseguest')),
                ('pov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_pov', to='simulator.houseguest')),
            ],
        ),
    ]
