# Generated by Django 3.2 on 2021-05-03 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0016_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('finalists', models.ManyToManyField(related_name='finalists', to='simulator.Houseguest')),
                ('jury', models.ManyToManyField(related_name='jury', to='simulator.Houseguest')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.houseguest')),
            ],
        ),
    ]
