# Generated by Django 3.2 on 2021-05-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0017_finale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('jury', models.ManyToManyField(related_name='game_jury', to='simulator.Houseguest')),
                ('players', models.ManyToManyField(related_name='game_players', to='simulator.Houseguest')),
                ('prejury', models.ManyToManyField(related_name='game_prejury', to='simulator.Houseguest')),
                ('weeks', models.ManyToManyField(to='simulator.Week')),
                ('winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.houseguest')),
            ],
        ),
    ]
