# Generated by Django 3.2 on 2021-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0018_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='weeks',
            field=models.ManyToManyField(default=[], to='simulator.Week'),
        ),
    ]
