# Generated by Django 3.2 on 2021-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0020_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='jury',
            field=models.ManyToManyField(default=[], related_name='game_jury', to='simulator.Houseguest'),
        ),
        migrations.AlterField(
            model_name='game',
            name='prejury',
            field=models.ManyToManyField(default=[], related_name='game_prejury', to='simulator.Houseguest'),
        ),
    ]
