# Generated by Django 3.2 on 2021-05-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0021_auto_20210504_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='inital_nominees',
            new_name='initial_nominees',
        ),
    ]
