# Generated by Django 3.2 on 2021-05-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_rename_inital_nominees_week_initial_nominees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evictionceremony',
            name='evicted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evicted_hg', to='simulator.houseguest'),
        ),
    ]
