# Generated by Django 3.2 on 2021-05-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0023_alter_evictionceremony_evicted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='weeks',
        ),
    ]
