# Generated by Django 3.2 on 2021-05-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0024_remove_game_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
